# ArgoCD UI 전용 포트 접근을 위한 Traefik IngressRoute 설정
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - argocd                         # ArgoCD 전용 엔트리포인트 사용
  routes:
    - match: Host(`*`) || PathPrefix(`/`)  # 모든 호스트와 경로 매칭
      kind: Rule
      services:
        - name: argocd-server
          port: 80