# ArgoCD UI 접근을 위한 Traefik IngressRoute 설정
# 외부에서 ArgoCD 웹 UI에 접근할 수 있도록 경로를 설정합니다.
# /argocd 경로로 접근하면 ArgoCD 서버로 리다이렉트됩니다.

# 1. IngressRoute: HTTP 트래픽 라우팅 규칙 정의
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server                  # IngressRoute 이름
  namespace: argocd                    # ArgoCD가 설치된 네임스페이스
spec:
  entryPoints:
    - web                              # HTTP 엔트리포인트 사용 (포트 80)
  routes:
    - match: PathPrefix(`/argocd`)     # /argocd 로 시작하는 요청을 매칭
      kind: Rule                       # 매칭 규칙 유형
      services:
        - name: argocd-server          # 대상 서비스 이름
          port: 80                     # 대상 서비스 포트
      middlewares:
        - name: argocd-stripprefix     # 사용할 미들웨어 (URL 경로 수정)
---
# 2. Middleware: URL 경로에서 프리픽스 제거
# ArgoCD는 루트 경로에서 동작하도록 설정되어 있어, /argocd 프리픽스를 제거해야 합니다.
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: argocd-stripprefix           # 미들웨어 이름
  namespace: argocd                  # ArgoCD가 설치된 네임스페이스
spec:
  stripPrefix:
    prefixes:
      - /argocd                      # URL에서 제거할 프리픽스 (/argocd/app → /app)