# Traefik RBAC (Role-Based Access Control) 설정
# Traefik이 Kubernetes API에 접근하여 리소스 정보를 읽고 인그레스 라우팅을 구성할 수 있도록 권한을 설정합니다.

# 1. ServiceAccount: Traefik 파드가 사용할 서비스 계정
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik                        # 서비스 계정 이름
  namespace: traefik-system            # 서비스 계정이 생성될 네임스페이스
---
# 2. ClusterRole: 전체 클러스터에서 Traefik이 필요로 하는 권한 정의
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik                        # 역할 이름
rules:
  # 기본 Kubernetes 리소스 접근 권한
  - apiGroups: [""]
    resources: ["services", "endpoints", "secrets"]  # 서비스, 엔드포인트, 비밀 정보
    verbs: ["get", "list", "watch"]                   # 읽기 전용 권한
  # Service Discovery를 위한 EndpointSlices 접근 권한
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]                   # 읽기 전용 권한
  # Ingress 리소스 접근 권한
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["get", "list", "watch"]                   # 읽기 전용 권한
  # Ingress 상태 업데이트 권한 (로드밸런서 IP 등)
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses/status"]
    verbs: ["update"]                              # 상태 업데이트 권한
  # Traefik 전용 CRD 리소스 접근 권한
  - apiGroups: ["traefik.io"]
    resources: ["ingressroutes", "ingressroutetcps", "ingressrouteudps", "middlewares", "middlewaretcps", "tlsoptions", "tlsstores", "traefikservices", "serverstransports", "serverstransporttcps"]
    verbs: ["get", "list", "watch"]                   # 읽기 전용 권한
---
# 3. ClusterRoleBinding: ServiceAccount와 ClusterRole을 연결
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik                        # 역할 바인딩 이름
roleRef:
  apiGroup: rbac.authorization.k8s.io  # RBAC API 그룹
  kind: ClusterRole                    # 바인딩할 역할 유형
  name: traefik                        # 바인딩할 ClusterRole 이름
subjects:
  - kind: ServiceAccount               # 대상 유형 (서비스 계정)
    name: traefik                      # 대상 ServiceAccount 이름
    namespace: traefik-system          # ServiceAccount가 있는 네임스페이스